name: "Write to InfluxDB"
description: |
  "This GitHub Action allows you to write data to InfluxDB, a time-series
  database. It's useful for storing and analyzing time-stamped data, such as
  metrics and events."
author: "Digdir Platform Team"

inputs:
  json:
    description: "Tags and fields data to be written to InfluxDB"
    required: true
  influxdb-url:
    description: "The URL of the InfluxDB instance where data will be"
    required: true
  influxdb-token:
    description: "The InfluxDB authentication token"
    required: true
  organization:
    description: "The organization name within InfluxDB"
    required: true
  bucket:
    description: "The name of the bucket in InfluxDB where data will be stored"
    required: true
  measurement-name:
    description: "The name of the measurement in InfluxDB"
    required: true
  precision:
    description: |
      "The precision of the timestamps in the data. Default is ns (nanoseconds)"
    default: "ns"

outputs:
  success:
    description: "True if data was successfully written to InfluxDB"

runs:
  using: node24
  main: dist/index.js
