name: "Write to InfluxDB"
description: "Provide a description here"
author: "Digdir Platform Team"

# Define your inputs here.
inputs:
  json:
    description: "Tags and fields data"
    required: true
  precision:
    default: "ns"
  influxdb-url:
    type: string
    required: true
  influxdb-token:
    type: string
    required: true
  organization:
    type: string
    required: true
  bucket:
    type: string
    required: true
  measurement-name:
    type: string
    required: true

# Define your outputs here.
outputs:
  success:
    description: "True if data was successfully written to InfluxDB"

runs:
  using: node20
  main: dist/index.js
