name: File Exists
description: |
  A GitHub Action that checks whether a specified file exists in the repository. It reports the result as an output, indicating whether the file exists or not, along with status messages. Useful for workflows that depend on the presence of certain files.
author: Digdir Platform Team
inputs:
  file-path:
    required: true
    type: string

outputs:
  exists:
    type: string

runs:
  using: composite

  steps:
    - name: Check if file exists
      id: check-if-file-exists
      shell: bash
      run: |
        set -o allexport; source "${{ github.action_path }}/file-exists.bash"; set +o allexport;

        file_exists ${{inputs.file-path}}
