name: Get Release Notes
description: |
  A GitHub Action that generates release notes based on the commits between two
  specified commit SHAs. The action takes inputs such as the repository name,
  head and base commit SHAs, and options for formatting the release notes. It
  outputs an array of release notes that can be used in subsequent steps of a
  workflow. Useful for automating the generation of release notes during
  deployment or release processes.
author: Digdir Platform Team

inputs:
  repository:
    description: "Name of application repository"
    required: true
  head:
    description: "Head commit SHA"
    required: true
  base:
    description: "Base commit SHA"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  show-pull-request-links:
    description: "Show PR numbers as links"
    required: false
    default: "false"
  pull-request-base-url:
    description: "Pull-request base URL"
    required: false
  show-jira-links:
    description: "Show Jira IDs as links"
    required: false
    default: "false"
  jira-base-url:
    description: "Jira base URL"
    required: false

outputs:
  release-notes:
    description: "Release notes array"

runs:
  using: node24
  main: dist/index.js
