name: Get Release Notes
description: |
  "..."
author: Digdir Platform Team
inputs:
  repository:
    description: Name of application repository
    required: true
    type: string
  head:
    description: Head commit SHA
    required: true
    type: string
  base:
    description: Base commit SHA
    required: true
    type: string
  github-token:
    description:
    required: true
    type: string
  show-pull-request-links:
    description: Show PR numbers as links
    required: false
    default: false
    type: boolean
  pull-request-base-url:
    description: Pull-request base URL
    required: false
    type: string
  show-jira-links:
    description;: Show Jira IDs as links
    required: false
    default: false
    type: boolean
  jira-base-url:
    description: Jira base URL
    required: false
    type: string

outputs:
  release-notes:
    description: Release notes array

runs:
  using: node20
  main: dist/index.js
