name: Write Deployment To Grafana
description:
author: Digdir Platform Team

inputs:
  dashboard-id:
    required: true
    type: string
  panel-id:
    required: true
    type: string
  annotation-text:
    required: true
    type: string
  grafana-token:
    required: true
    type: string
  annotation-url:
    type: string
    default: ""

runs:
  using: composite

  steps:
    - name: Write deployment text annotation to Grafana
      id: write-annotation-to-grafana
      shell: bash
      env:
        GRAFANA_URL: https://digdir.grafana.net/api/annotations/
      run: |
        create_json_payload() {
          local dashboard_id=$1
          local panel_id=$2
          local annotation_text=$3
          local annotation_url=$4

          if [ -n "$annotation_url" ]; then
              annotation_text="<a href=\"$annotation_url\">$annotation_text</a>"
          fi

          jq -n \
              --arg dashboard_id "$dashboard_id" \
              --arg panel_id "$panel_id" \
              --arg text "$annotation_text" \
              '{"dashboardId": $dashboard_id | tonumber, "panelId": $panel_id | tonumber, "text": $text}'
          }

        ANNOTATION_JSON=$(create_json_payload "${{ inputs.dashboard-id }}" "${{ inputs.panel-id }}" "${{ inputs.annotation-text }}" "${{ inputs.annotation-url }}")

        RESPONSE_HTTP_CODE=$(
          curl \
            -X POST ${{ env.GRAFANA_URL }} \
            --write-out "%{http_code}\n" \
            -o /dev/null \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ inputs.grafana-token }}" \
            -d "$ANNOTATION_JSON"
        );  

        echo "response-http-code=$RESPONSE_HTTP_CODE" >> $GITHUB_OUTPUT

    - name: Log outputs
      id: log-outputs
      shell: bash
      run: |
        if [ "${{ steps.write-annotation-to-grafana.outputs.response-http-code }}" == "200" ]; then
          echo "- Annotation added to Grafana :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "- Failed to add annotation to Grafana (HTTP response: ${{ steps.write-annotation-to-grafana.outputs.response-http-code }}) :x:" >> "$GITHUB_STEP_SUMMARY"
        fi

        {
          echo '  ```'
          echo "  dashboard-id: ${{ inputs.dashboard-id }}"
          echo "  panel-id: ${{ inputs.panel-id }}"
          echo "  annotation-text: \"${{ inputs.annotation-text }}\""
          echo "  annotation-url: \"${{ inputs.annotation-url }}\""
          echo '  ```'
        } >> "$GITHUB_STEP_SUMMARY"

        if [ "${{ steps.write-annotation-to-grafana.outputs.response-http-code }}" != "200" ]; then
          exit 1
        fi
