name: Send Slack notification
description: |
  This GitHub Action is designed to notify designated Slack channels about workflow events. 
  It enables teams to stay informed about GitHub Actions workflows, 
  facilitating rapid response and resolution.
author: Digdir Platform Team
inputs:
  slack-channel-id:
    type: string
    required: true
  slack-bot-token:
    type: string
    required: true
  failed:
    type: string
    required: false
    default: "false"
  application-name:
    type: string
    required: false
  environment:
    type: string
    required: false
  product:
    type: string
    required: false
  jira-id:
    type: string
    required: false
  version:
    type: string
    required: false
  repository:
    type: string
    required: false
  pr-number:
    type: string
    required: false
  initiated-by:
    type: string
    required: false

runs:
  using: composite

  steps:
    - name: Checkout tools
      uses: actions/checkout@v4
      with:
        repository: felleslosninger/github-actions
        sparse-checkout: |
          send-slack-notification/tools/github-context-utils.js
        sparse-checkout-cone-mode: false

    - name: Get commit message
      id: commit-message
      uses: actions/github-script@v7
      with:
        script: |
          const Utils = require('./send-slack-notification/tools/github-context-utils.js');
          const message = Utils.getCommitMessage(${{ toJson(github) }});
          return message;

    - name: Notify on failure
      if: |
        inputs.slack-channel-id != '' && 
        inputs.failed == 'true'
      id: notify-on-failure
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        payload: |
          {
            "text": "GitHub Action failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":x: GitHub Action - Workflow failed\n*${{ fromJson(steps.commit-message.outputs.result) }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow*\n${{ github.workflow_ref }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Run id*\n*<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>*"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Committer*\n${{ github.actor }}"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }

    - name: Notify on success
      if: |
        inputs.slack-channel-id != '' &&
        inputs.failed == 'false'
      id: notify-on-success
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        payload: |
          {
            "text": "Successfully deployed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":white_check_mark: Application successfully deployed"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Application name:*\n${{ inputs.application-name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Environment:*\n${{ inputs.environment }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Product:*\n${{ inputs.product }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Jira id:*\n<https://digdir.atlassian.net/browse/${{ inputs.jira-id }}|${{ inputs.jira-id }}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Version:*\n${{ inputs.version }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Application PR:*\n<https://github.com/${{ inputs.repository }}/pull/${{ inputs.pr-number }}|#${{ inputs.pr-number }}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Initiated by:*\n${{ inputs.initiated-by }}"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }
