name: Send Slack notification
description: |
  This GitHub Action is designed to notify designated Slack channels about workflow events. 
  It enables teams to stay informed about GitHub Actions workflows, 
  facilitating rapid response and resolution.
author: Digdir Platform Team
inputs:
  slack-channel-id:
    type: string
    required: true
  slack-bot-token:
    type: string
    required: true

runs:
  using: composite

  steps:
    - name: Checkout JS Tools
      uses: actions/checkout@v4
      with:
        repository: felleslosninger/github-workflows
        path: tools

    - name: Get commit message
      id: commit-message
      uses: actions/github-script@v7
      with:
        script: |
          const Utils = require('./tools/.github/js/github-context-utils.js');
          const message = Utils.getCommitMessage(${{ toJson(github) }});
          return message;

    - name: Notify
      if: ${{ inputs.slack-channel-id != '' }}
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        payload: |
          {
            "text": "Github Action failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action - Workflow failed\n*${{ fromJson(steps.commit-message.outputs.result) }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow*\n${{ github.workflow_ref }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Run id*\n*<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>*"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Committer*\n${{ github.actor }}"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }
