name: Send Slack notification
description: |
  This GitHub Action is designed to notify designated Slack channels about
  workflow events. It enables teams to stay informed about GitHub Actions
  workflows, facilitating rapid response and resolution.
author: Digdir Platform Team

inputs:
  slack-channel-id:
    description: "ID of the Slack channel to send notifications to"
    required: true
  slack-bot-token:
    description: "Slack Bot User OAuth Token with permissions to post in the channel"
    required: true
  failed:
    description: "Indicates whether the workflow has failed or succeeded (true/false)"
    required: false
    default: "false"
  application-name:
    description: "Name of the application being deployed"
    required: false
  environment:
    description: "Environment where the application is deployed"
    required: false
  product:
    description: "Product to which the application belongs"
    required: false
  jira-id:
    description: "Jira ID associated with the deployment"
    required: false
  version:
    description: "Version of the application being deployed"
    required: false
  repository:
    description: "Repository where the application is hosted"
    required: false
  pr-number:
    description: "Pull request number"
    required: false
  initiated-by:
    description: "User who initiated the workflow"
    required: false

runs:
  using: composite

  steps:
    - name: Checkout tools
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
      with:
        repository: felleslosninger/github-actions
        sparse-checkout: |
          send-slack-notification/tools/github-context-utils.js
        sparse-checkout-cone-mode: false

    - name: Get commit message
      id: commit-message
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # pin@v9.0.0
      with:
        script: |
          const Utils = require('./send-slack-notification/tools/github-context-utils.js');
          const message = Utils.getCommitMessage(${{ toJson(github) }});
          return message;

    - name: Notify on failure
      if: |
        inputs.slack-channel-id != '' &&
        inputs.failed == 'true'
      id: notify-on-failure
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # pin@v3.0.3
      with:
        # Using bot token
        method: chat.postMessage
        token: ${{ inputs.slack-bot-token }}
        payload: |
          {
            "channel": "${{ inputs.slack-channel-id }}",
            "text": "GitHub Action failed",
            "attachments": [
              {
                "color": "#e96d76",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":x: GitHub Action - Workflow failed\n*${{ fromJson(steps.commit-message.outputs.result) }}*"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow*\n${{ github.workflow_ref }}"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repository*\n${{ github.repository }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Run id*\n*<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>*"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Committer*\n${{ github.actor }}"
                      }
                    ]
                  },
                  {
                    "type": "divider"
                  }
                ]
              }
            ]
          }

    - name: Notify on success
      if: |
        inputs.slack-channel-id != '' &&
        inputs.failed == 'false'
      id: notify-on-success
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # pin@v3.0.3
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-bot-token }}
        payload: |
          {
            "channel": "${{ inputs.slack-channel-id }}",
            "text": "Successfully deployed",
            "attachments": [
              {
                "color": "#18be52",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":white_check_mark: Application successfully deployed"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Application name:*\n${{ inputs.application-name }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Environment:*\n${{ inputs.environment }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Product:*\n${{ inputs.product }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Jira id:*\n${{ ((inputs.jira-id == '' || inputs.jira-id == 'Dependabot') && 'N/A') || format('<https://digdir.atlassian.net/browse/{0}|{0}>', inputs.jira-id) }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Version:*\n${{ inputs.version }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Application PR:*\n${{ (inputs.pr-number == '' && 'N/A') || format('<https://github.com/{0}/pull/{1}|#{1}>', inputs.repository, inputs.pr-number) }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Initiated by:*\n${{ inputs.initiated-by }}"
                      }
                    ]
                  },
                  {
                    "type": "divider"
                  }
                ]
              }
            ]
          }
