name: Run actionlint
description: Runs actionlint - a static checker for GitHub Actions workflow files
author: Digdir Platform Team
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0

    - name: Download actionlint
      id: download-actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      shell: bash

    - name: Check workflow files
      run: ${{ steps.download-actionlint.outputs.executable }} -color
      shell: bash
