name: Validate Pull Request Title
description: |
  "The Validate Pull Request Title GitHub Action checks if the title of a pull request meets specified criteria,
  including length constraints and required prefixes.
  It helps maintain consistency and clarity in pull request titles within your repository."
author: Digdir Platform Team

inputs:
  pull-request-title:
    description: "The title of the pull request to validate"
    required: true
  case-sensitive-prefix:
    description: "Indicates whether the prefix validation should be case-sensitive. If true, the prefixes must match exactly as specified; if false, the validation will ignore case differences"
    default: "true"
  max-length-title:
    description: "The maximum allowed length for the pull request title. If the title exceeds this length, it will be considered invalid"
    default: "100"
  min-length-title:
    description: "The minimum allowed length for the pull request title. If the title is shorter than this length, it will be considered invalid"
    default: "10"
  allowed-prefixes:
    description: "A comma-separated list of allowed prefixes for the pull request title"
    required: true

outputs:
  is-valid:
    description: Indicates if the title is valid or not
  error-message:
    description: |
      A detailed message indicating why the pull request title is invalid.
      This may include information such as exceeding maximum length, not meeting minimum length, or lacking required prefixes.

runs:
  using: node24
  main: dist/index.js
