name: Run Bats Tests

on:
  push:
    branches:
      - "*"

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5
        with:
          submodules: "true"

      - name: Run Bats Tests
        id: run-bats-tests
        run: |
          BATS_OUTPUT=$(./test/bats/bin/bats ./test/*.bats)
          BATS_OUTPUT="${BATS_OUTPUT//$'\n'/'%0A'}"

          echo "test-results=$BATS_OUTPUT" >> $GITHUB_OUTPUT

      - name: Display Test Results
        id: summary
        run: |
          TEST_RESULTS="${{ steps.run-bats-tests.outputs.test-results }}"
          TEST_RESULTS="${TEST_RESULTS//$'%0A'/\\n}"

          {
            echo "## Test results"
            echo '```'
            echo -e "$TEST_RESULTS"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
