name: Lint Codebase

on:
  pull_request:
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed
  push:
    branches:
      - main
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed

permissions: read-all

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - "write-to-influxdb/"
          - "github-app-token/"
          - "publish-release-notes/"
          - "get-release-notes/"
          - "validate-pull-request-title/"
          # Add more folders as needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.folder }}/.node-version
          cache-dependency-path: ${{ matrix.folder }}/package-lock.json
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ matrix.folder }}

      - name: Check Licenses
        run: npm run lisenssjekk
        working-directory: ${{ matrix.folder }}

      - name: Run Prettier Check
        run: npm run format:check
        working-directory: ${{ matrix.folder }}

      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ matrix.folder }}

      - name: Run TypeScript Type Check
        run: npx tsc --noEmit
        working-directory: ${{ matrix.folder }}
