name: Lint Codebase

on:
  pull_request:
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed
  push:
    branches:
      - main
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed

permissions:
  contents: read
  packages: read
  statuses: write

env:
  FILTER_REGEX_EXCLUDE: .*dist/.*

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - "write-to-influxdb/"
          - "github-app-token/"
          - "publish-release-notes/"
          - "get-release-notes/"
          - "validate-pull-request-title/"
          # Add more folders as needed

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v4.1.4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # pin@v4.0.4
        with:
          node-version-file: ${{ matrix.folder }}/.node-version
          cache-dependency-path: ${{ matrix.folder }}/package-lock.json
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ matrix.folder }}

      - name: Lint Codebase
        uses: super-linter/super-linter/slim@b92721f792f381cedc002ecdbb9847a15ece5bb8 # pin@v7.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          FILTER_REGEX_INCLUDE: .*${{ matrix.folder }}.*
