name: Run Jest Tests

on:
  pull_request:
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed
  push:
    branches:
      - main
    paths:
      - "write-to-influxdb/**"
      - "github-app-token/**"
      - "publish-release-notes/**"
      - "get-release-notes/**"
      - "validate-pull-request-title/**"
      # Add more folders as needed

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - "write-to-influxdb/"
          - "github-app-token/"
          - "publish-release-notes/"
          - "get-release-notes/"
          - "validate-pull-request-title/"
          # Add more folders as needed

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v4.1.4
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # pin@v4.0.4
        with:
          node-version-file: ${{ matrix.folder }}/.node-version
          cache-dependency-path: ${{ matrix.folder }}/package-lock.json
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ matrix.folder }}

      - run: npm run test
        working-directory: ${{ matrix.folder }}
