name: Run Bats Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS testing framework
        id: setup
        uses: mig4/setup-bats@v1.2.0

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Run Bats Tests
        id: run-bats-tests
        run: |
          BATS_OUTPUT=$(./test/bats/bin/bats ./test/*.bats)
          BATS_OUTPUT="${BATS_OUTPUT//$'\n'/'%0A'}"

          echo "test-results=$BATS_OUTPUT" >> $GITHUB_OUTPUT

      - name: Display Test Results
        id: summary
        run: |
          TEST_RESULTS="${{ steps.run-bats-tests.outputs.test-results }}"
          TEST_RESULTS="${TEST_RESULTS//$'%0A'/\\n}"

          {
            echo "## Test results"
            echo '```'
            echo -e "$TEST_RESULTS"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
