name: Run Bats Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bats Tests
        run: bats ./**/*.bats
